services:
  n8n:
    build: .
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8nbotti-production.up.railway.app/
      - N8N_HOST=${N8N_HOST}
      - N8N_RUNNERS_ENABLED=true
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      # Variables para la base de datos
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST}
      - DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE}
      - DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD}
      - NODE_FUNCTION_ALLOW_EXTERNAL=pg
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
